In [1]:
import pandas as pd

In [14]:
df_2019 = pd.read_csv('pandas-workout-data/data/nyc_taxi_2019-07.csv',
                      usecols=['passenger_count', 'payment_type', 'total_amount'])

df_2020 = pd.read_csv('pandas-workout-data/data/nyc_taxi_2020-07.csv',
                      usecols=['passenger_count', 'payment_type', 'total_amount'])

In [19]:
df_2020.head()

passenger_count  payment_type  total_amount
0              1.0           2.0          9.30
1              1.0           1.0         27.80
2              1.0           2.0         22.30
3              1.0           1.0         14.16
4              1.0           2.0          7.80

In [20]:
df_2019.shape

(6310419, 3)

In [8]:
df_2019.shape

(6310419, 3)

In [9]:
df_2019['year'] = 2019
df_2019.head()

passenger_count  payment_type  total_amount  year
0              1.0           1.0          4.94  2019
1              1.0           2.0         20.30  2019
2              1.0           1.0         70.67  2019
3              1.0           1.0         66.36  2019
4              0.0           1.0         15.30  2019

In [10]:
df_2020['year'] = 2020
df_2020.head()

passenger_count  payment_type  total_amount  year
0              1.0           2.0          9.30  2020
1              1.0           1.0         27.80  2020
2              1.0           2.0         22.30  2020
3              1.0           1.0         14.16  2020
4              1.0           2.0          7.80  2020

In [13]:
df = pd.concat([df_2019, df_2020], 
               axis=0)

df.tail()

passenger_count  payment_type  total_amount  year
800407              NaN           NaN         83.50  2020
800408              NaN           NaN         19.78  2020
800409              NaN           NaN         38.45  2020
800410              NaN           NaN         29.77  2020
800411              NaN           NaN         51.90  2020

In [37]:
# how many rides were taken in 2019 vs. 2020
df['year'].value_counts()[2019] - df['year'].value_counts()[2020]

5510007

In [27]:
# how much money was collected on rides in 2019 vs. 2020
total_amount_2019 = df.loc[df['year'] == 2019, 'total_amount'].sum()
total_amount_2020 = df.loc[df['year'] == 2020, 'total_amount'].sum()

In [38]:
total_amount_2019 - total_amount_2020


108848979.24000001

In [32]:
df.loc[df['year'] == 2019, 'passenger_count'].value_counts(normalize=True)

1.0    0.697987
2.0    0.151958
3.0    0.044481
5.0    0.040510
6.0    0.024171
4.0    0.022259
0.0    0.018623
7.0    0.000005
8.0    0.000004
9.0    0.000003
Name: passenger_count, dtype: float64

In [33]:
df.loc[df['year'] == 2020, 'passenger_count'].value_counts(normalize=True)

1.0    0.767402
2.0    0.123243
3.0    0.029527
0.0    0.026446
5.0    0.023194
6.0    0.019587
4.0    0.010589
7.0    0.000007
8.0    0.000003
9.0    0.000001
Name: passenger_count, dtype: float64

the proportion of trips with only 1 passenger went from 69.8 percent in 2019 to 76.7 percent in 2020

In [34]:
# did people us less cash in 2019 than in 2020
df.loc[df['year'] == 2019, 'payment_type'].value_counts(normalize=True)

1.0    0.704883
2.0    0.287060
3.0    0.005654
4.0    0.002404
Name: payment_type, dtype: float64

In [35]:
df.loc[df['year'] == 2020, 'payment_type'].value_counts(normalize=True)

1.0    0.665705
2.0    0.320559
3.0    0.009245
4.0    0.004490
Name: payment_type, dtype: float64

according to this people actually used cash slightly more frequently in 2020